backend:
  name: git-gateway
  branch: master
media_folder: static/img
public_folder: /img
logo_url: >-
  https://megaphone-logo-uploads.s3.amazonaws.com/1550525574604_devLogo_white.png
collections:
  - name: blog
    label: Blog Post
    folder: src/pages/a
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - label: Template Key
        name: templateKey
        widget: hidden
        default: blog-post
      - label: Title
        name: title
        widget: string
      - label: Author
        name: author
        widget: select
        options:
          - label: Blogwise Staff
            value: blogwiseStaff
      - label: Publish Date
        name: date
        widget: datetime
      - label: Thumbnail
        name: thumbnail
        widget: image
        required: false
        allow_multiple: false
      - label: Description
        name: description
        widget: text
      - label: Body
        name: body
        widget: markdown
      - label: Topics
        name: tags
        widget: select
        multiple: true
        options:
          - label: ReactJS
            value: 222d6736-b1e4-477c-c36-ce9f07c1562b
          - label: 'Entrepreneurship '
            value: 573b4271-c513-47d3-825-ce443604dea5
          - label: Marketing
            value: 9b10d33a-a52b-4cf1-a265-0e8c574d07d
  - name: pages
    label: Pages
    files:
      - file: src/pages/about/index.md
        label: About
        name: about
        fields:
          - label: Template Key
            name: templateKey
            widget: hidden
            default: about-page
          - label: Title
            name: title
            widget: string
          - label: Body
            name: body
            widget: markdown
