backend:
  name: git-gateway
  branch: master
publish_mode: editorial_workflow
media_folder: static/img
public_folder: /img
logo_url: ''
collections:
  - name: blog
    label: Blog Post
    folder: src/pages/a
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - label: Template Key
        name: templateKey
        widget: hidden
        default: blog-post
      - label: Title
        name: title
        widget: string
      - label: Author
        name: author
        widget: select
        options:
          - label: Blogwise Staff
            value: blogwiseStaff
      - label: Publish Date
        name: date
        widget: datetime
      - label: Thumbnail
        name: thumbnail
        widget: image
        required: false
        allow_multiple: false
      - label: Description
        name: description
        widget: text
      - label: Body
        name: body
        widget: markdown
      - label: Tags
        name: tags
        widget: select
        multiple: true
        options: []
  - name: pages
    label: Pages
    files:
      - file: src/pages/about/index.md
        label: About
        name: about
        fields:
          - label: Template Key
            name: templateKey
            widget: hidden
            default: about-page
          - label: Title
            name: title
            widget: string
          - label: Body
            name: body
            widget: markdown
